#+TITLE:时刻淘上线部署手册
时刻淘上线部署手册共分为两大部分，系统环境构建与项目部署。 
** 系统环境构建
   购买阿里云服务器并搭建 Centos7 最小安装镜像，假设 ip 地址为 120.89.67.90。
   针对初始化系统的构建，可以分为一下四个部分：1、Centos7 环境搭建，2、软件安装，3、监控系统，4、域名解析。下面针对每一部分进行详细讲解。
*** Centos7 环境搭建
**** 基础软件安装
     #+BEGIN_SRC shell
     yum remove firewall -y
     yum install gcc* make vim iptables-service policycoreutils-python -y
     #+END_SRC
**** 用户设置
     分别创建管理员用户、ssh 登录用户、web 执行用户，并设定随机密码
***** 修改 root 用户密码
      #+BEGIN_SRC shell
      yum -y install expect
      mkpasswd -l 16 -d 2 -C 2 -s 2 -v root
      #+END_SRC
      上诉代码会设置用户 root 密码形似 wdcK0smaE5kfu_{e
***** 管理员用户
      #+BEGIN_SRC shell
      useradd babyfunlab -M -U
      mkpasswd -l 16 -d 2 -C 2 -s 2 -v babyfunlab
      #+END_SRC
      上述命令将会创建没有家目录且组为 babyfunlab 的新用户 babyfunlab 并通过 mkpasswd 命令生成一个 16 位的随机密码，其中-l 密码长度，默认 9;-d 密码中包含数字个数，默认 2；-c 密码中包含小写字母个数，默认 2；-C 密码中包含大写字母个数，默认 2；-s 密码中包含特殊字符的个数，默认 1；-v 指定用户。
      设定 babyfunlab 用户为管理员用户，拥有 sudo 权限:
      #+BEGIN_SRC shell
      vim /etc/sudoers
      babyfunlab    ALL=(ALL)    ALL
      #+END_SRC
***** ssh 登录用户
      #+BEGIN_SRC shell
      useradd bfl -M -U
      mkpasswd -l 16 -d 2 -C 2 -s 2 -v bfl
      #+END_SRC
***** web 用户
      #+BEGIN_SRC shell
      useradd www -M -U
      #+END_SRC
      创建 web 项目根目录
      #+BEGIN_SRC shell
      mkdir /home/www
      chown -R www:www /home/www/
      #+END_SRC
**** ssh 安全设置
     ssh 默认 22 端口，修改大于 20000 以上端口，假设为 22907。
     默认情况下，Centos7 的 SELinux 是 enforcing 模式，可以通过 sestatus -v 查看，如果不是该模式通过一下方式修改：
     #+BEGIN_SRC shell
     vim /etc/sysconfig/selinux
     SELINUX=enforcing
     reboot
     #+END_SRC
     默认 Centos7 的 SELinux 设置 ssh 端口为 22，如果想修改端口，则可以使用 semanage 命令，该命令有 policycoreutils-python 提供。
     通过下面命令查看 sshd 在 SELinux 中的端口：
     #+BEGIN_SRC shell
     semanage port -l | grep ssh
     ssh_port_t tcp 22
     #+END_SRC
     将 22907 添加到 SELinux 的 ssh_port_t 中：
     #+BEGIN_SRC shell
     semanage port -a -t ssh_port_t -p tcp 22907
     #+END_SRC
     进一步修改 ssh 配置
     #+BEGIN_SRC shell
     vim /etc/ssh/sshd_config
     Port 22907
     LoginGraceTime 30 
     MaxAuthTries 3 
     Protocol 2 
     PermitRootLogin no
     AllowUsers bfl
     #+END_SRC
     上述配置中 LoginGraceTime 允许一次登录花费 30 秒，超时不允许访问，需重新登录；MaxAuthTries 把错误尝试的次数限制为 3 次，3 次之后拒绝登录尝试；Protocol 2 禁止使用比较弱的协议，PermitRootLogin no 禁止 root 用户登录，AllowUsers username 只允许 bfl 用户登录，修改完配置重启 sshd 服务。
     #+BEGIN_SRC shell
     systemctl restart sshd.service
     systemctl enable sshd.service
     #+END_SRC
**** 防火墙设置
     只开放 80、443、22907(ssh 端口)端口
     #+BEGIN_SRC shell
     vim /etc/sysconfig/iptables
     -A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
     -A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
     -A INPUT -p tcp -m state --state NEW -m tcp --dport 22907 -j ACCEPT

     systemctl restart iptables.service
     systemctl enable iptables.service
     #+END_SRC
      
